# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_person_events'),
        ('events', '0002_event_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(to='register.Person'),
        ),
    ]
