# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20161011_2110'),
        ('events', '0003_auto_20161011_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
