# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20161011_2110'),
        ('events', '0004_auto_20161011_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(to='register.Person'),
        ),
    ]
