# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161011_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='events'),
        ),
    ]
