# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_person_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
    ]
