# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20161011_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='identity',
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
